# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:8.14.1
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install
      - run:
          name: Build
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                printenv >> ~/repo/config/.env.production && npm run build:production
              fi
              if [ $CIRCLE_BRANCH = 'staging' ]; then
                export FIREBASE_API_KEY=$FIREBASE_API_KEY_STAGING
                export FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN_STAGING
                export FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL_STAGING
                export FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID_STAGING
                export DEPLOY_ENV=staging
                printenv >> ~/repo/config/.env.staging && npm run build:staging
              fi
              if [ $CIRCLE_BRANCH = 'develop' ]; then
                printenv >> ~/repo/config/.env.development && npm run build:development
              fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - .

  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "23:6a:3d:12:bb:77:c0:b8:18:cc:72:56:8d:c4:91:a5"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Firebase deploy
          command: node scripts/deploy.js --branch $CIRCLE_BRANCH
      - run:
          name: Storybook deploy
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            npm run deploy:storybook

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - staging
                - master

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
